server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://ep-odd-frog-ai77a49l-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_zWBJ7opCPAG9
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

jwt:
  secret: mySuperSecretKeyForJwtGeneration12345
  expiration: 86400000