server.port=${PORT:8082}
server.error.include-message=always
server.error.include-binding-errors=always

spring.datasource.url=jdbc:postgresql://dpg-d6knh81aae7s73ahk30g-a:5432/job_db_hx6c
spring.datasource.username=job_db_hx6c_user
spring.datasource.password=8pXUG4QTmYYoupzSWrfobDxU41MFPnvE

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect