server.port=8084

resume.service.url=http://localhost:8082
job.service.url=http://localhost:8083

# ===============================

# EMAIL CONFIGURATION (GMAIL SMTP)

# ===============================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=project.yasha16@gmail.com
spring.mail.password=vqef afnl mmba oklu

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
