# ===============================
# SERVER PORT (Render dynamic port)
# ===============================
server.port=${PORT:8080}

# ===============================
# POSTGRESQL DATABASE (Render DB)
# ===============================
spring.datasource.url=jdbc:postgresql://dpg-d6knh81aae7s73ahk30g-a.singapore-postgres.render.com:5432/job_db_hx6c
spring.datasource.username=job_db_hx6c_user
spring.datasource.password=8pXUG4QTmYYoupzSWrfobDxU41MFPnvE
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# ===============================
# CONNECTION POOL (Recommended)
# ===============================
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000